# 1. Enable Mouse #####
set -g mouse on

# 2. Vi Mode for Copy Mode #####
setw -g mode-keys vi

# 3. Enter Copy Mode with Prefix + [ (default, no global [ binding) #####
unbind -n C-[

# 4. Long Scrollback Buffer #####
set -g history-limit 100000  # 100k lines

# 5. Yank to Windows Clipboard (using clip.exe) #####
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "clip.exe"
bind -T copy-mode-vi Enter send -X copy-pipe-and-cancel "clip.exe"

# 5b. Mouse selection also copies to clipboard (Windows/WSL/clip.exe) #####
bind -n MouseDrag1Pane copy-mode      # Mouse selection enters copy-mode
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "clip.exe"

# 6. NERD FONTS / Statusline Appearance #####
set -g @icon_date  ""
set -g @icon_time  ""
set -g @icon_user  ""
set -g @icon_ip    ""
set -g @icon_sesh  ""
set -g @icon_prefix  "#[fg=colour208][PREFIX]#[fg=default] "
set -g status-style "bg=default,fg=white"
set -g window-status-current-style "bg=default,fg=white,bold"
set -g status-interval 1
set -g status-left-length 50
set -g status-left "#{?client_prefix,#{@icon_prefix},}#{@icon_sesh} #S "
set -g status-right-length 150
set -g status-right "#{@icon_user} #(whoami) │ #{@icon_ip} #(hostname -I | awk '{print $1}') │ #{@icon_date} %a, %Y-%m-%d │ #{@icon_time} %H:%M:%S "

# 7. Visual/UX Copy Settings #####
set -g set-clipboard off   # Clipboard handled by our keybinds
set -g mode-style "bg=colour236,fg=white"
set -g display-panes-time 1000
set -ga terminal-features 'xterm-256color:RGB'
set -s escape-time 0

# Start at 1 for window and panes, and renumber if delete in the middle
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Bind to Prefix + r to reload, and display "Reloaded!"
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# Toggle last session
bind-key L switch-client -l

# Find session
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

# If split, preserve the path of current pane
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# If new window, prompt name
bind c command-prompt -p "Window Name:" "new-window -n '%%'"
bind C command-prompt -p "New Session:" "new-session -A -s '%%'"
bind C command-prompt -p "New Session:" "new-session -A -s '%%' ; command-prompt -p 'Window Name:' 'rename-window %%'"

bind -T root F12 \
  set prefix None \;\
  set key-table off \;\
  set status-style "fg=#505050" \;\
  if -F '#{pane_in_mode}' 'send-keys -X cancel' \;\
  refresh-client -S

bind -T off F12 \
  set -u prefix \;\
  set -u key-table \;\
  set -u status-style \;\
  refresh-client -S
