gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - white
      - bold
    inactiveBorderColor:
      - default
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
